#include <magic.h>

enum {
	$MAGIC_NONE = MAGIC_NONE,
	$MAGIC_DEBUG = MAGIC_DEBUG,
	$MAGIC_SYMLINK = MAGIC_SYMLINK,
	$MAGIC_COMPRESS = MAGIC_COMPRESS,
	$MAGIC_DEVICES = MAGIC_DEVICES,
	$MAGIC_MIME_TYPE = MAGIC_MIME_TYPE,
	$MAGIC_CONTINUE = MAGIC_CONTINUE,
	$MAGIC_CHECK = MAGIC_CHECK,
	$MAGIC_PRESERVE_ATIME = MAGIC_PRESERVE_ATIME,
	$MAGIC_RAW = MAGIC_RAW,
	$MAGIC_ERROR = MAGIC_ERROR,
	$MAGIC_MIME_ENCODING = MAGIC_MIME_ENCODING,
	$MAGIC_MIME = MAGIC_MIME,
	$MAGIC_APPLE = MAGIC_APPLE,
	$MAGIC_NO_CHECK_COMPRESS = MAGIC_NO_CHECK_COMPRESS,
	$MAGIC_NO_CHECK_TAR = MAGIC_NO_CHECK_TAR,
	$MAGIC_NO_CHECK_SOFT = MAGIC_NO_CHECK_SOFT,
	$MAGIC_NO_CHECK_APPTYPE = MAGIC_NO_CHECK_APPTYPE,
	$MAGIC_NO_CHECK_ELF = MAGIC_NO_CHECK_ELF,
	$MAGIC_NO_CHECK_TEXT = MAGIC_NO_CHECK_TEXT,
	$MAGIC_NO_CHECK_CDF = MAGIC_NO_CHECK_CDF,
	$MAGIC_NO_CHECK_TOKENS = MAGIC_NO_CHECK_TOKENS,
	$MAGIC_NO_CHECK_ENCODING = MAGIC_NO_CHECK_ENCODING,

	$MAGIC_NO_CHECK_ASCII = MAGIC_NO_CHECK_ASCII,

	$MAGIC_NO_CHECK_FORTRAN = MAGIC_NO_CHECK_FORTRAN,
	$MAGIC_NO_CHECK_TROFF = MAGIC_NO_CHECK_TROFF
};
